modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="cn.aminorz.jigsaw.jigsaw"
version="1.15.2-1.2"
displayName="Aminor_z's Jigsaw Lib"
logoFile="banner.png"
authors="Aminor_z"
description='''

'''
[[dependencies.cn.aminorz.jigsaw.jigsaw]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cn.aminorz.jigsaw.jigsaw]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
